spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3306/Market
spring.datasource.username=root
spring.datasource.password=Screwuhacker123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=true
